### ISSUE TITLE
r metal armor sprite offset

### ISSUE THREAD

**Issue by Serxule** [Afterglow-Ss13/afterglow-ss13#149]
---- Testmerges: ----

---- Reproduction: ----

reinforced metal armor sprite is offset this is so poainful
---- Screenshots: ----
![Screenshot_680](https://github.com/Afterglow-Ss13/afterglow-ss13/assets/64584757/d84289a2-f4d7-4244-ac6f-b64ada94b35e)

**Comment by Zero-Percent-Angel** [comment]
Fixed in next dev iteration
