### ISSUE TITLE
rebel raider armor is error sprite when worn

### ISSUE THREAD

**Issue by Serxule** [Afterglow-Ss13/afterglow-ss13#150]
---- Testmerges: ----

---- Reproduction: ----
title

---- Screenshots: ----
![Screenshot_681](https://github.com/Afterglow-Ss13/afterglow-ss13/assets/64584757/ce9867d3-b1d6-435f-a748-ed0f29d4462b)

---- Additional context: ----

**Comment by Zero-Percent-Angel** [comment]
Fixed in next dev iteration
